server:
  port: 9000

oauth2:
  google:
    client:
      clientId: 392952476879-jlmdialpqb787gh27rp786ketuuivij6.apps.googleusercontent.com
      clientSecret: X92EfAwILkbE0QLSDKieqrIF
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
      useCurrentUri: false # in ordert to get dynamic redirect URL set useCurrentUri to false
      preEstablishedRedirectUri: http://localhost:9000/googleLogin
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: false